[book]
authors = ["4meta5, Joshy Orndorff"]
language = "en"
multilingual = false
src = "text"
title = "Substrate Recipes"
description = "A Hands-On Cookbook for Aspiring Blockchain Chefs"

[output.html]
additional-js = [
  ".analytics/load.js",
  ".analytics/config.js",
  ".analytics/klaro.min.js"
]
theme = "src/theme"

[output.linkcheck]
follow-web-links = true
warning-policy = "warn"
exclude = [
	# A few one-off sites that load fine in browser but trip up the link checker with 404
	"https://crates.io/",
	"www4\\.comp\\.polyu\\.edu\\.hk/~csxluo/",
	"www.cse.huji.ac.il/~nati/",
	# Links to code in new recipe PRs always fail because the code is not merged yet
	"github\\.com/substrate-developer-hub/recipes/tree/",
]
