name: Build Book

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build-book:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.3.7'
        # mdbook-version: 'latest'

    - name: Build Book
      run: mdbook build
