[package]
authors = ['Joshy Orndorff']
edition = '2018'
name = 'basic-pow'
repository = 'https://github.com/substrate-developer-hub/recipes'
version = "2.0.0-rc3"
description = 'A Substrate node that demonstrates minimal proof of work consensus'
license = "GPL-3.0-or-later"

[package.metadata.substrate]
categories = [
	"Node",
	"PoW",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc3"

[[bin]]
name = 'basic-pow'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'
parity-scale-codec = '1.3.0'
sha3 = "0.8"
rand = { version = "0.7", features = ["small_rng"] }
sc-consensus = '0.8.0-rc3'
sc-consensus-pow = '0.8.0-rc3'
sp-consensus-pow = '0.8.0-rc3'
sc-client-api = '2.0.0-rc3'
sp-blockchain = '2.0.0-rc3'
sp-timestamp = '2.0.0-rc3'
sc-basic-authorship = '0.8.0-rc3'
sc-cli = '0.8.0-rc3'
sc-executor = '0.8.0-rc3'
sc-network = '0.8.0-rc3'
sc-service = '0.8.0-rc3'
sc-transaction-pool = '2.0.0-rc3'
sp-consensus = '0.8.0-rc3'
sp-core = '2.0.0-rc3'
sp-inherents = '2.0.0-rc3'
sp-runtime = '2.0.0-rc3'
sp-transaction-pool = '2.0.0-rc3'
sha3pow = { path = '../../consensus/sha3pow' }

# This node is compatible with any of the runtimes below
# ---
# Common runtime configured with most Recipes pallets.
runtime = { package = "super-runtime", path = "../../runtimes/super-runtime" }

# Runtime with custom weight and fee calculation.
# runtime = { package = "weight-fee-runtime", path = "../../runtimes/weight-fee-runtime"}

# Runtime with custom runtime-api (custom API only used in rpc-node)
# runtime = { package = "api-runtime", path = "../../runtimes/api-runtime" }
# ---

[build-dependencies]
vergen = '3.0.4'
substrate-build-script-utils = '2.0.0-rc3'
