[package]
name = "single-value"
version = "2.0.0-rc3"
repository = 'https://github.com/substrate-developer-hub/recipes'
authors = ["4meta5"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "A pallet that demonstrates storing values in Substrate storage"

[package.metadata.substrate]
categories = [
	"pallet",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc3"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
]

[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.3.0' }
frame-support = { version = '2.0.0-rc3', default-features = false }
frame-system  = { version = '2.0.0-rc3', default-features = false }
sp-runtime = { version = '2.0.0-rc3', default-features = false }

[dev-dependencies]
sp-core = { version = '2.0.0-rc3', default-features = false }
sp-io = { version = '2.0.0-rc3', default-features = false }
